__author__ = "Kuan-Hao Chao"
__contact__ = "kuanhao.chao@gmail.com"
__copyright__ = "Copyright 2023, Kuan-Hao Chao"
__credits__ = ["Kuan-Hao Chao"]
__date__ = "2023/07/26"
__deprecated__ = False
__email__ =  "kuanhao.chao@gmail.com"
__license__ = "MIT"
__maintainer__ = "developer"
__status__ = "Kuan-Hao Chao"
__version__ = "1.0.3"