__author__ = "Kuan-Hao Chao"
__contact__ = "kuanhao.chao@gmail.com"
__copyright__ = "Copyright 2023, $COMPANY_NAME"
__credits__ = ["One developer", "And another one", "Kuan-Hao Chao"]
__date__ = "2023/07/01"
__deprecated__ = False
__email__ =  "kuanhao.chao@gmail.com"
__license__ = "MIT"
__maintainer__ = "developer"
__status__ = "Kuan-Hao Chao"
__version__ = "0.3.1"